name: Run Python Tests

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # ou a versão que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de ter um requirements.txt

      - name: Run tests with pytest and generate report
        run: |
          pytest --html=report.html --self-contained-html  # Gera um relatório em HTML

      - name: Upload test report
        uses: actions/upload-artifact@v4  # Atualize para a versão v4
        with:
          name: test-report
          path: report.html  # Caminho para o relatório gerado
